"""chunking_settings

Revision ID: a849e5f21516
Revises: 2adc0b597dcd
Create Date: 2025-02-14 17:15:25.930884

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a849e5f21516"
down_revision = "2adc0b597dcd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "knowledge_bases", sa.Column("chunking_config", sa.JSON(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("knowledge_bases", "chunking_config")
    # ### end Alembic commands ###
